sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - ./buildDocs.sh
  - touch ./build/doc/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
