sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen build/doc/ExchangeToolkit.config

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ExchangeToolkit/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master